---
title: "Nonparametrics Homework 4"
author: "Forrest walker"
output:
  html_notebook: default
  html_document: default
---

## Question 1

For a paired nonparametric test I will first compute the differences in the pairs, and then find every combination if the paired data was random, and find the distrobution of the difference in the permutations. 
```{r}
library(gtools)
Q1_t1 <- c(100,250,50,80)
Q1_t2 <- c(112,240,58,82)

Q1_obs <- Q1_t1-Q1_t2
Q1_pos <- (Q1_obs[2])
Q1_data <- abs(Q1_obs)
Q1_signs <- c(-1,1)
Q1_Msigns <- permutations(2,4,Q1_signs,repeats.allowed=T)
dim(Q1_Msigns)
y <- unique(Q1_Msigns)

Q1_d <- Q1_Msigns %*%Q1_data
hist(Q1_d,breaks=20)
```


## Question 2

```{r}
a <- 10000
Q2_t1 <- c(2,3,4,4,3,1,3,4,4,5,3,4,2,2,4,3,4,2,2)
Q2_t2 <- c(2,4,4,4,4,4,3,5,4,4,4,5,4,2,5,5,4,1,2)
Q2_obs <- Q2_t1-Q2_t2
Q2_data <- abs(Q2_obs)
Q2_signs <- c(-1,1)
Q2_Msigns <- matrix(NA,a,19)


for(i in 1:a){
  Q2_Msigns[i,] <- sample(Q2_signs,19,replace=T)
}
dim(Q2_Msigns)
Q2_d <- Q2_Msigns %*% Q2_data
Q2_count <- 0
for(i in 1:a){
  if(sum(Q2_d[i])<=sum(Q2_obs)){Q2_count <- Q2_count+1}
}
Q2_count/a

```


## Question 3

```{r}
library(gtools)
Q3_t1 <- c(100,250,50,80)
Q3_t2 <- c(112,240,58,82)

Q3_obs <- Q3_t1-Q3_t2
Q3_obs
Q3_abs <- abs(Q3_obs)
Q3_Robs <- rank(Q3_abs)
Q3_SRobs <- Q3_Robs*(c(0,1,0,0))
Q3_SRobs
Q3_SRpos <- (Q3_obs[2])
Q3_data <- abs(Q3_obs)
Q3_signs <- c(0,1)
Q3_Msigns <- permutations(2,4,Q3_signs,repeats.allowed=T)
Q3_Msigns
dim(Q3_Msigns)

Q3_d <- Q3_Msigns %*%Q3_Robs
Q3_d
hist(Q3_d,breaks=20)
```

## Question 4
Using SRplus
```{r}
Q4_before <- c(89,90,87,98,120,85,97)
Q4_after <- c(76,101,84,86,105,84,93)
Q4_obs <- Q4_before-Q4_after
Q4_obs
Q4_abs <- abs(Q4_obs)
Q4_Robs <- rank(Q4_abs)
Q4_SRplus_obs <-sum(Q4_Robs*(c(1,0,1,1,1,1,1)))
Q4_signs <- c(0,1)
Q4_Msigns <- permutations(2,7,Q4_signs,repeats.allowed=T)
dim(Q4_Msigns)
Q4_d <- Q4_Msigns %*% Q4_Robs

Q4_count <- 0
for(i in 1:128){
  if(Q4_d[i]>=Q4_SRplus_obs){
  Q4_count <- Q4_count+1
  }
}
Q4_count/128
t.test(Q4_before,Q4_after,paired=T,alt="greater")
```

## Question 5

```{r}
Q5_t1 <- c(2,3,4,4,3,1,3,4,4,5,3,4,2,2,4,3,4,2,2)
Q5_t2 <- c(2,4,4,4,4,4,3,5,4,4,4,5,4,2,5,5,4,1,2)
Q5_obs <- Q5_t2-Q5_t1
Q5_obs
Q5_abs <- abs(Q5_obs)
Q5_Rabs <- rank(Q5_abs)
Q5_SRplus_obs <- sum(Q5_Rabs*(c(0,1,0,0,1,1,0,1,0,0,1,1,1,0,1,1,0,0,0)))
Q5_signs <- c(0,1)
Q5_Msigns <- matrix(NA,a,19)
a <- 10000
for(i in 1:a){
  Q5_Msigns[i,] <- sample(Q5_signs,19,replace=T)
}
dim(Q5_Msigns)
Q5_d <- Q5_Msigns %*% Q5_Rabs
Q5_count <- 0
for(i in 1:a){
  if(sum(Q5_d[i])>=sum(Q5_SRplus_obs)){Q5_count <- Q5_count+1}
}
Q5_count/a
```


## Question 7

### Part A

```{r}
Q7_b1 <- c(1.5,1.8,1.9)
Q7_b2 <- c(2.1,2.0,2.5)
Q7_b3 <- c(1.9,2,2.5)
Q7_b4 <- c(2.8,2.7,2.6)
Q7_b5 <- c(1.4,1.6,2.1)
Q7_b6 <- c(1.8,2.3,2.4)
Q7_M <- cbind(Q7_b1,Q7_b2,Q7_b3,Q7_b4,Q7_b5,Q7_b6)

Q7_f<- function(data){
  for(i in 1:nrow(data)){
  return(sum((mean(data[i,]))^2))
  }
}
Q7_SSXobs <- c(rep(NA,3))
for(i in 1:3){
  Q7_SSXobs[i] <- sum((mean(Q7_M[i,]))^2)
}
Q7_count <- 0
Q7_SSXobs

a <- 10000
Q7_d <- matrix(NA,a,3)
Q7_Dperm <- matrix(NA,3,6)

for(i in 1:a){
  for(j in 1:6){
  Q7_Dperm[,j] <- sample(Q7_M[,j])
  }
  for(k in 1:3){
  Q7_d[,k] <- sum((mean(Q7_Dperm[k,]))^2)
} 
  if(sum(Q7_d[i,])>=sum(Q7_SSXobs)){
    Q7_count <- Q7_count+1
  }
}
Q7_count/a
```

### Part B

```{r}
Q7_b1 <- c(1.5,1.8,1.9)
Q7_b2 <- c(2.1,2.0,2.5)
Q7_b3 <- c(1.9,2,2.5)
Q7_b4 <- c(2.8,2.7,2.6)
Q7_b5 <- c(1.4,1.6,2.1)
Q7_b6 <- c(1.8,2.3,2.4)
Q7_values <- c(Q7_b1,Q7_b2,Q7_b3,Q7_b4,Q7_b5,Q7_b6)
Q7_blocks <- c(rep("b1",3),rep("b2",3),rep("b3",3),rep("b4",3),rep("b5",3),rep("b6",3))
Q7_treat <- c(rep("sep.1",6),rep("sep.15",6),rep("sep.30",6))
Q7_df <- data.frame(Q7_values,Q7_blocks,Q7_treat)

Q7_aov <- aov(Q7_values~Q7_blocks+Q7_treat,data=Q7_df)
summary(Q7_aov)
```



## Question 8

```{r}
Q7_b1 <- c(1.5,1.8,1.9)
Q7_b2 <- c(2.1,2.0,2.5)
Q7_b3 <- c(1.9,2,2.5)
Q7_b4 <- c(2.8,2.7,2.6)
Q7_b5 <- c(1.4,1.6,2.1)
Q7_b6 <- c(1.8,2.3,2.4)
Q8_M <- cbind(Q7_b1,Q7_b2,Q7_b3,Q7_b4,Q7_b5,Q7_b6)

Q8_rmean <- rowMeans(Q8_M)
Q8_cmean <- colMeans(Q8_M)
Q8_obs_maxdiff <- max(abs(Q8_rmean- Q8_cmean))

a <- 10000
Q8_perm <- matrix(NA,3,6)
Q8_perm_mdiff <- rep(NA,a)
for(i in 1:a){
  Q8_perm[,1] <- sample(Q8_M[,1])
  Q8_perm[,2] <- sample(Q8_M[,2])
  Q8_perm[,3] <- sample(Q8_M[,3])
  Q8_perm[,4] <- sample(Q8_M[,4])
  Q8_perm[,5] <- sample(Q8_M[,5])
  Q8_perm[,6] <- sample(Q8_M[,6])
  
  Q8_perm_rmean <- rowMeans(Q8_perm)
  Q8_perm_cmean <- colMeans(Q8_perm)
  Q8_perm_mdiff[i] <- max(abs(Q8_perm_rmean -Q8_perm_cmean))
}

quantile(Q8_perm_mdiff, .9)
quantile(Q8_perm_mdiff, .95)

hist(Q8_perm_mdiff,
     xlab = "max",
     freq = FALSE,breaks = 25)
abline(v = quantile(max.diffs, .9), col = 2, lwd = 2)
abline(v = quantile(max.diffs, .95), col = 4, lwd = 2)

```



## Question 9

```{r}
Q9_b1 <- c(1.5,1.8,1.9)
Q9_b2 <- c(2.1,2.0,2.5)
Q9_b3 <- c(1.9,2,2.5)
Q9_b4 <- c(2.8,2.7,2.6)
Q9_b5 <- c(1.4,1.6,2.1)
Q9_b6 <- c(1.8,2.3,2.4)
Q9_M <- cbind(Q7_b1,Q7_b2,Q7_b3,Q7_b4,Q7_b5,Q7_b6)

Q9_rank <- apply(Q9_M, 2, rank)
Q9_rmean <- rowMeans(Q9_rank)
Q9_obs <- (12*6 / (3*(3+1))) * sum((Q9_rmean - ((3+1)/ 2))^2)

a <- 10000
Q9_rperm <- matrix(NA,3,6)
Q9_perm <- rep(NA, a)
for(i in 1:a){
  Q9_rperm[,1] <- sample(Q9_rank[,1])
  Q9_rperm[,2] <- sample(Q9_rank[,2])
 Q9_rperm[,3] <- sample(Q9_rank[,3])  
  Q9_rperm[,4] <-sample(Q9_rank[,4])
  Q9_rperm[,5] <- sample(Q9_rank[,5])
  Q9_rperm[,6] <- sample(Q9_rank[,6])

  Q9_perm_rmean <- rowMeans(Q9_rperm)
  Q9_perm[i] <- (12*6 / (3*(3+1))) * sum((Q9_perm_rmean - ((3+1)/ 2))^2)
}
Q9_count <- sum(Q9_perm >= Q9_obs)
Q9_count/a

```




## Question 10

```{r}
Q10_a <- c(4,5,2,3)
Q10_b <- c(3,2,5,4)
Q10_c <- c(1,3,1,2)
Q10_d <- c(2,1,3,1)
Q10_e <- c(6,6,4,5)
Q10_f <- c(5,4,6,6)

Q10_M<- cbind(Q10_a,Q10_b,Q10_c,Q10_d,Q10_e,Q10_f)

Q10_rmean <- rowMeans(Q10_M)
Q10_obs <- (12*6 / (4*(4+1))) * sum((Q10_rmean - ((4+1)/ 2))^2)

a <- 10000
Q10_d <- rep(NA,a)
Q10_perm <- matrix(NA,4,6)
Q10_perm
for(i in 1:a){
  Q10_perm[,1] <- sample(Q10_M[,1])
  Q10_perm[,2] <- sample(Q10_M[,2])
  Q10_perm[,3] <- sample(Q10_M[,3])  
  Q10_perm[,4] <- sample(Q10_M[,4])
  Q10_perm[,5] <- sample(Q10_M[,5])
  Q10_perm[,6] <- sample(Q10_M[,6])
  
  Q10_perm_rmean<- rowMeans(Q10_perm)
   Q10_d[i] <- (12*6 / (4*(4+1))) * sum((Q10_perm_rmean - ((4+1)/ 2))^2)
}
Q10_count <- sum(Q10_d[i] >= Q10_obs)
Q10_count/a

```
